### ISSUE TITLE
File package constants has wrong permissions

### ISSUE THREAD

**Issue by adelowo** [spiral/common#5]
https://github.com/spiral/common/blob/master/source/Spiral/Files/FilesInterface.php#L23 says `0655`.. That allows execution of the file.. And this is even considering the fact that the constant says `READONLY`.

I propose it be changed to `664` or `644`

**Comment by wolfy-j** [comment]
I forgot what was the reason to set `5` for non-group users. I will check it with existed tests.

**Comment by adelowo** [comment]
Ping

**Comment by wolfy-j** [comment]
Oh yeah, thx for reminder :) Will check it after holidays, feel free to to create PR.

**Comment by wolfy-j** [comment]
RUNTIME now 666, READONLY 644
